### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by binbibi** [inmyfree/readability#1]
I see your project in [jinri.info](http://jinri.info/index.php/DaiArticle/index/8222'),Great,The API will always work?I really like it, I have a VPS, and I can deploy the project in my VPS,Can you help?

**Comment by inmyfree** [comment]
1.这个api不会一直运行，现在只是我挂载做demo的
2.安装  
    这个项目是基于nodejs环境，请先安装nodejs，
    你可以在你vps上通过git clone https://github.com/inmyfree/readability.git 下载源码，
    然后cd到readability目录，通过npm install既可以安装依赖
    最后通过node app.js启动既可以，也可以通过forever来维持运行

**Comment by binbibi** [comment]
谢谢回复。。。可以关闭这个issue了。。。
